# Loki Configuration for Alloy POC
# Updated for latest Loki version compatibility

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# By default, Loki will send anonymous usage data to Grafana Labs
# Disable this by uncommenting the following line:
# analytics:
#   reporting_enabled: false

# Frontend configuration for query performance
frontend:
  max_outstanding_per_tenant: 2048
  compress_responses: true
  log_queries_longer_than: 5s

# Query scheduler for better resource management
query_scheduler:
  max_outstanding_requests_per_tenant: 2048

# Ingester configuration
ingester:
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 1GB
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s

# Storage configuration
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-shipper-active
    cache_location: /loki/tsdb-shipper-cache
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks

# Compactor for index cleanup
compactor:
  working_directory: /loki/tsdb-shipper-compactor
  compaction_interval: 10m
  retention_enabled: false

# Limits configuration
limits_config:
  # Structured metadata
  allow_structured_metadata: false
  
  # Ingestion limits
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_line_size: 256000
  max_line_size_truncate: false
  
  # Query limits
  max_query_length: 721h
  max_query_parallelism: 32
  max_streams_per_user: 10000
  max_global_streams_per_user: 5000
  
  # Retention
  retention_period: 168h  # 7 days
  
  # Per-stream limits
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  
  # Cardinality limits
  max_label_name_length: 1024
  max_label_value_length: 4096
  max_label_names_per_series: 30
  
  # Reject old samples
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  
  # Split queries
  split_queries_by_interval: 15m
  
  # Max entries limit
  max_entries_limit_per_query: 5000
  
  # Max concurrent tail requests
  max_concurrent_tail_requests: 10

# Table manager for retention
table_manager:
  retention_deletes_enabled: false

# Analytics
analytics:
  reporting_enabled: false

# Tracing configuration
tracing:
  enabled: false

# Memberlist configuration for clustering (disabled for single instance)
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members: []

# Chunk store configuration
chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 100
      ttl: 1h
  write_dedupe_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 100
      ttl: 1h

# Query frontend worker (disabled for single instance)
# frontend_worker:
#   frontend_address: 127.0.0.1:9095
#   grpc_client_config:
#     max_send_msg_size: 104857600  # 100MB

# Distributor configuration
distributor:
  ring:
    kvstore:
      store: inmemory