# Grafana Datasources Configuration for Beyla POC

apiVersion: 1

datasources:
  # Prometheus - Métricas
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ''
      timeInterval: '15s'
      queryTimeout: '60s'
      defaultEditor: 'code'
      disableRecordingRules: false
      incrementalQuerying: true
      incrementalQueryOverlapWindow: '10m'
      exemplarTraceIdDestinations:
        - name: 'Jaeger'
          datasourceUid: 'jaeger-uid'
          urlDisplayLabel: 'View in Jaeger'
    uid: prometheus-uid

  # Jaeger - Traces
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki-uid'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags: ['job', 'instance', 'pod', 'namespace']
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: 'method="$${__span.tags.method}"'
      tracesToMetrics:
        datasourceUid: 'prometheus-uid'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      nodeGraph:
        enabled: true
      search:
        hide: false
      spanBar:
        type: 'Tag'
        tag: 'http.status_code'
    uid: jaeger-uid

  # Loki - Logs (opcional, se configurado)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: 'jaeger-uid'
          matcherRegex: 'traceID=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'
        - datasourceUid: 'prometheus-uid'
          matcherRegex: 'service_name=(\w+)'
          name: 'Service Metrics'
          url: 'service_name="$${__value.raw}"'
          urlDisplayLabel: 'View Metrics'
      maxLines: 1000
      timeout: '60s'
    uid: loki-uid

  # Alloy - Métricas internas
  - name: Alloy
    type: prometheus
    access: proxy
    url: http://alloy:12345/metrics
    editable: true
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      timeInterval: '15s'
      queryTimeout: '30s'
    uid: alloy-uid

  # TestData - Para demonstrações
  - name: TestData
    type: testdata
    access: proxy
    editable: true
    jsonData:
      csvContent: |
        time,value,metric
        2023-01-01T00:00:00Z,100,requests_total
        2023-01-01T00:01:00Z,150,requests_total
        2023-01-01T00:02:00Z,200,requests_total
    uid: testdata-uid